CREATE DATABASE MATH_BACKEND; 

USE MATH_BACKEND; 

CREATE TABLE USER_INFO (
	USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLES VARCHAR(20) NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL
);


CREATE TABLE QUESTION_INFO (
	QUESTION_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ASKED_ID INTEGER,
    QUESTION TEXT NOT NULL,
    IMAGE_PATH VARCHAR(100) NOT NULL,
    DATE_TIME_POSTED VARCHAR(50) NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL, 
    FOREIGN KEY (USER_ASKED_ID) REFERENCES USER_INFO(USER_ID)
);

CREATE TABLE ANSWER_INFO (
	ANSWER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TUTOR_ANSWERED_ID INTEGER,
    QUESTION_ANSWERED_ID INTEGER,
    DATE_TIME_ANSWERED VARCHAR(50) NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL, 
	FOREIGN KEY(TUTOR_ANSWERED_ID) REFERENCES USER_INFO(USER_ID),
    FOREIGN KEY(QUESTION_ANSWERED_ID) REFERENCES QUESTION_INFO(QUESTION_ID)
);


